server:
  #存在包含层级时，下一级一般习惯空2格，属性名与属性值一般习惯空1格
  #配置项目的访问端口
  port: 80

spring:
  #web中的相关配置
  mvc:
    view:
      #配置访问jsp页面的前后缀
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  #数据源的配置
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hotel?useSSL=false&useUnicode=true&characterEncoding=utf-8
      username: root
      password: root

#配置日志的输出
logging:
  level:
    org:
      #日志信息的打印
      springframework: DEBUG,error
    com:
      java:
        mapper: DEBUG

#配置pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#配置相关的mybatis
mybatis:
  #扫描加载到所有的mapper.xml文件
  mapper-locations: classpath:mapper/*.xml
  #给实体封装类配置别名：默认就是类名
  #type-aliases-package: com.java.entity
zhang:
  imagesPath: file:C:\Users\Administrator\Pictures\picture\


